version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: subdb
      POSTGRES_USER: subuser
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/subdb
      SPRING_DATASOURCE_USERNAME: subuser
      SPRING_DATASOURCE_PASSWORD: secret
    ports:
      - "8080:8080"

volumes:
  pgdata: