spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/subdb
    username: subuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
  flyway:
    enabled: true
logging:
  level:
    org.hibernate.SQL: DEBUG